### ISSUE TITLE
code typo error

### ISSUE THREAD

**Issue by wenmingMeng** [jianfenglihg/UnOpticalFlow#1]
https://github.com/jianfenglihg/UnOpticalFlow/blob/2acf5022fac3842271491ee99d6e5e986a91f4e7/loss_functions.py#L452
i think this line should be :image_gradients_x_up = gradient_x_up(img)
the same error occurred in line 453,454,455,504,506.
The training command in README.md could be trained normally?

**Comment by jianfenglihg** [comment]
Thank you for pointing this error，I will fix the bug and update the relevant hyperparameters as soon as possible.
I have tested the training command on my local machine, it can be trained normally
