### ISSUE TITLE
When I ran the demo in the test file, I found that the Model_depth_pose model was indeed

### ISSUE THREAD

**Issue by zouzhiwei217** [jianfenglihg/UnOpticalFlow#10]

**Comment by jianfenglihg** [comment]
As readme said, please set --task as "kitti_flow", not "demo"
python test.py --config_file ./config/kitti.yaml --gpu [gpu_id] --mode flow --task **kitti_flow** --pretrained_model [path/to/your/model]

actually there are some code belong to another repository,  i did't clean up, sorry for misleading you.

**Comment by zouzhiwei217** [comment]
Thank you very much for replying to my question. I want to see the optical flow diagram of any set of pictures, so I think it is to set the task to demo, and set the position of the picture (--image_path) and the position of the output optical flow diagram (- -result_dir), and the Model_depth_pose missing in the tes.py file I have found in the code of another paper. I don't know if there is a mistake in my thinking. Please point me out my mistake. Thank you!

**Comment by zouzhiwei217** [comment]
Thank you very much for replying to my question. I want to see the optical flow diagram of any set of pictures, so I think it is to set the task to demo, and set the position of the picture (--image_path) and the position of the output optical flow diagram (- -result_dir), and the Model_depth_pose missing in the tes.py file I have found in the code of another paper. I don't know if there is a mistake in my thinking. Please point me out my mistake. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianfenglihg/UnOpticalFlow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午2:30
收件人:&nbsp;"jianfenglihg/UnOpticalFlow"<UnOpticalFlow@noreply.github.com&gt;;
抄送:&nbsp;"邹智伟"<369513570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jianfenglihg/UnOpticalFlow] When I ran the demo in the test file, I found that the Model_depth_pose model was indeed (#10)





 
As readme said, please set --task as "kitti_flow", not "demo"
 python test.py --config_file ./config/kitti.yaml --gpu [gpu_id] --mode flow --task kitti_flow --pretrained_model [path/to/your/model]
 
actually there are some code belong to another repository,  i did't clean up, sorry for misleading you.

**Comment by zouzhiwei217** [comment]
Hello, I would like to ask you the usefulness of the log.pkl file created in train.py. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianfenglihg/UnOpticalFlow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午2:30
收件人:&nbsp;"jianfenglihg/UnOpticalFlow"<UnOpticalFlow@noreply.github.com&gt;;
抄送:&nbsp;"邹智伟"<369513570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jianfenglihg/UnOpticalFlow] When I ran the demo in the test file, I found that the Model_depth_pose model was indeed (#10)





 
As readme said, please set --task as "kitti_flow", not "demo"
 python test.py --config_file ./config/kitti.yaml --gpu [gpu_id] --mode flow --task kitti_flow --pretrained_model [path/to/your/model]
 
actually there are some code belong to another repository,  i did't clean up, sorry for misleading you.
