### ISSUE TITLE
Validation problem durning training

### ISSUE THREAD

**Issue by wenmingMeng** [jianfenglihg/UnOpticalFlow#3]
https://github.com/jianfenglihg/UnOpticalFlow/blob/3caa4d6f7f472da07a96d9d452546893c0eced3c/datasets/validation_flow.py#L76

I think this line should be 
`tgt_img_path =  self.root.joinpath('data_scene_flow_multiview', self.phase, 'image_2',str(index).zfill(6)+'_10.png')`
like line 113 in https://github.com/anuragranj/cc/blob/master/datasets/validation_flow.py。

The image_2 file folder in kitti2015 contains left image in stereo pair,and image_3 contains right images。And the gt flow images in kitti2015 are provide for left image sequences。So，the images in image_3 for inference flow and calculation epe metric with gt flow may occur some error。

By the way，would u mind provide a detail log file durning training？
I traning in kittiraw with your training command in readme，the epe metric decrease very slowly。
![image](https://user-images.githubusercontent.com/20263828/81769278-c6c3f300-950f-11ea-85d2-0a83a6ed1134.png)
The epe metric in kitti2015 is  about 25 after 38 epoch。Is this normal？

looking forward to your reply！

**Comment by wenmingMeng** [comment]
老哥，你哪个学校的啊。。有没有时间加个微信聊聊，有问题问问你啊。。

**Comment by jianfenglihg** [comment]
wechat: tjchlhg
