### ISSUE TITLE
EPE metric calculation on kitti2015 training set problem

### ISSUE THREAD

**Issue by wenmingMeng** [jianfenglihg/UnOpticalFlow#4]
https://github.com/jianfenglihg/UnOpticalFlow/blob/3caa4d6f7f472da07a96d9d452546893c0eced3c/test_flow_back2future.py#L337
hi，i think there is a calculation error in this fuction。 
i think u should use varible epe_occ to calculate epe of full image. So the line 
https://github.com/jianfenglihg/UnOpticalFlow/blob/3caa4d6f7f472da07a96d9d452546893c0eced3c/test_flow_back2future.py#L358
should be like this :
   ` avg_epe = (epe_occ.sum())/(valid_occ.sum() + 1e-6)`
Furthermore i use the model u provide in README.md and test on kitti2015 training set，the epe metric is ：
![image](https://user-images.githubusercontent.com/20263828/82117213-52a07e00-97a1-11ea-9e61-4977d381333f.png)
which mean  : 
EPE_ALL:1=10.9
EPE_NOC:3.52
EPE_OCC:42.5

More details about epe metric calculation on kitti2015 could be found here:
https://github.com/baidu-research/UnDepthflow/blob/b818a8706890cdbe2ed7774f67b99d8a0e957288/eval/evaluate_flow.py#L102

**Comment by jianfenglihg** [comment]
Thanks for your testing, it seems that this code has serious problems, I will try to solve.
