### ISSUE TITLE
Problems running code

### ISSUE THREAD

**Issue by zouzhiwei217** [jianfenglihg/UnOpticalFlow#7]
Excuse me, is the code training successful? I want to study your code carefully, because my research needs to use your optical flow results.

**Comment by jianfenglihg** [comment]
Thanks for you question, the version management did not do well before, now I added the tag, and update readme.

yes, It can be trained successful.  I have test on my machine just now, like this:
![image](https://user-images.githubusercontent.com/49476280/107142193-1123b480-6968-11eb-9cf0-98fc37de2e3b.png)

In addition, I uploaded the pre-trained weights on the dataset.

**Comment by zouzhiwei217** [comment]
Hello, I have received your reply. Thank you very much for answering my question, I will try to train your network soon. But I am worried that there will be some other problems. Can you give me your email? I want to contact you in time. Thank you very much.
