### ISSUE TITLE
about forward and backward warp

### ISSUE THREAD

**Issue by btwbtm** [jianfenglihg/UnOpticalFlow#8]
Hi, Nice work! But I am confused about some codes.

First, can you explain why there are three input images? In my understanding, we have image 1 and image 2.
https://github.com/jianfenglihg/UnOpticalFlow/blob/823434a68a7fade8a94e44e14bde1a7a64dedd78/core/networks/model_flow_paper.py#L209

Second, it seems you use warp_flow() function for both forward and backward warp operations. Specifically, you call grid_sample() function. However, I think grid_sample only makes sense for backward warp. Please point out where I am wrong.
https://github.com/jianfenglihg/UnOpticalFlow/blob/823434a68a7fade8a94e44e14bde1a7a64dedd78/core/networks/structures/net_utils.py#L46

Thx!

**Comment by jianfenglihg** [comment]
The input of  network is two frame, but we use three frame in training. We feed **(img, imgl)** and **(img, imgr)** into the network separately, and we obtain backward and forward optical flow respectively.  During warping, we use backward optical flow and imgl to reconstruct img, and in the same way, we use forward optical flow and imgr to reconstruct img.

**Comment by btwbtm** [comment]
Hi jianfeng, thx a lot for your prompt reply! I thought this the repo for Occulsion Aware Unsupervised Learning of Optical Flow. Now I know you have different setting. Thx!
